### ISSUE TITLE
Hiding/removing likes,rt,comment option

### ISSUE THREAD

**Issue by dontpnc** [FixTweet/FxTwitter#591] opened 2024-01-06 00:38 UTC
How to remove likes/rt/comment from display when using fxtwitter.com?

g.fxtwitter.com not working.

![IMG_2570](https://github.com/FixTweet/FxTwitter/assets/154376108/148bcc8c-e91a-4452-a335-b9e324d9be8a)

**Comment by dangeredwolf** [comment] 2024-01-07 06:43
Duplicate of #581

**Closed by dangeredwolf** 2024-01-07 06:43 UTC
