### ISSUE TITLE
Translate Embed functionalty seems to no longer be working.

### ISSUE THREAD

**Issue by BaconCatBug** [FixTweet/FxTwitter#869] opened 2024-06-28 10:52 UTC
![image](https://github.com/FixTweet/FxTwitter/assets/4897163/d3dd063c-4796-4c82-b5a8-3778117587db)

**Comment by azatoth** [comment] 2024-07-16 15:48
Looks like it still works for `fxtwitter.com` domain, but not under `fixupx.com` domain
![image](https://github.com/user-attachments/assets/bdc3aaf1-17b5-4f9d-98f1-f00ad60af5c9)
![image](https://github.com/user-attachments/assets/6d67c50f-c8ab-4c87-b48f-241712421cd0)

**Comment by Proaxel** [comment] 2024-07-16 22:27
Neither of the domains work for me.
![image](https://github.com/user-attachments/assets/4886fd13-b9df-457e-bc4f-008e85505543)
![image](https://github.com/user-attachments/assets/4df0a338-68b3-4a57-8e18-5410b79428a4)

**Comment by Gestrid** [comment] 2024-07-24 17:33
I can confirm that it's not working on either domain for me, either, so it doesn't seem to just be a weird glitch.

![Screenshot_20240724-133051](https://github.com/user-attachments/assets/29ef2acd-60c0-4681-835b-9cdccf3531dc)

![Screenshot_20240724-133108](https://github.com/user-attachments/assets/6d92636d-d50f-45b4-a89d-e7218041af7c)

**Comment by Gestrid** [comment] 2024-07-24 17:43
Hmm... On a whim, I tried adding "www." to the domain name and got it to work on the "fxtwitter" domain on one tweet I tested it on, but not the other.

The same method did not work on the "fixupx" domain.

![Screenshot_20240724-133828](https://github.com/user-attachments/assets/e1798c0a-0d1b-4221-a80f-5c53831d354c)
![Screenshot_20240724-133844](https://github.com/user-attachments/assets/4e8bd51c-e91a-4d6b-95a4-6a60e0aa8eef)
![Screenshot_20240724-133903](https://github.com/user-attachments/assets/b5a582c8-ff81-459c-8e6e-71a983b97095)
![Screenshot_20240724-133924](https://github.com/user-attachments/assets/ed94fe44-b0b5-41bc-b60c-a3efd0716c4a)

**Comment by dangeredwolf** [comment] 2024-07-25 00:40
I just pushed a change, does translation work again for you?

**Comment by azatoth** [comment] 2024-07-25 01:02
> I just pushed a change, does translation work again for you?

Tested against both fixupx and fxwtitter and they both did show a translation this time

**Comment by Gestrid** [comment] 2024-07-25 02:07
Just retested the same tweets as before. They're now translating properly.

**Comment by Proaxel** [comment] 2024-07-25 02:15
Seems to be working now on my end, thanks to those involved!

**Comment by dangeredwolf** [comment] 2024-08-06 00:43
Closing again as it's working again, if issues come up again feel free to reopen!

**Closed by dangeredwolf** 2024-08-06 00:43 UTC
Labels: regression, embeds, can repro
