### ISSUE TITLE
Display the date of the post

### ISSUE THREAD

**Issue by YJB-Gay** [FixTweet/FxTwitter#703] opened 2024-03-04 16:20 UTC
Add the timestamp of the post in the footer![Screenshot_20240304-111915_1.png](https://github.com/FixTweet/FxTwitter/assets/129620824/2fade6cd-6dfb-453a-afc9-9d3196914da3)

**Comment by dangeredwolf** [comment] 2024-03-05 12:40
Duplicate of #464, Discord afaik does not have a way to pass this information along in website embeds unfortunately, it is a feature of bot embeds

**Closed by dangeredwolf** 2024-03-05 12:40 UTC
